version: '3.8'

services:
  frontend:
    build: ./autoarch-frontend
    container_name: frontend
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - api
    networks:
          - autoarch-network

  api:
    build: ./api
    container_name: api
    ports:
      - 8000:8000
    restart: always
    environment:
      - OPENAI_API_KEY
    networks:
          - autoarch-network

networks:
    autoarch-network:
        driver: bridge
